List<String> tips = [
  "Stay hydrated by drinking enough water throughout the day.",
  "Aim for at least 30 minutes of exercise most days of the week.",
  "Include a variety of colorful fruits and vegetables in your diet.",
  "Get enough sleep to allow your body to rest and recover.",
  "Practice stress-reduction techniques like meditation or deep breathing.",
  "Avoid processed foods high in added sugars and trans fats.",
  "Don't skip breakfast; it's an important meal to kickstart your day.",
  "Maintain a regular sleep schedule to improve sleep quality.",
  "Limit your caffeine and alcohol intake for better overall health.",
  "Make time for regular health check-ups and screenings.",
  "Practice good hand hygiene by washing your hands frequently, especially before meals.",
  "Limit your salt intake to help maintain healthy blood pressure.",
  "Find a physical activity you enjoy, so you're more likely to stick with it.",
  "Prioritize mental health by talking to someone when you're feeling overwhelmed.",
  "Try to get some sunlight every day to boost your vitamin D levels.",
  "Incorporate whole grains like brown rice and whole wheat bread into your diet.",
  "Don't forget to floss your teeth regularly for good oral health.",
  "Take short breaks during work to stretch and avoid sitting for too long.",
  "Laugh often; it's good for your mood and overall well-being.",
  "Experiment with healthy cooking methods like grilling or steaming.",
  "Inspect your feet daily for any cuts, sores, or blisters, and keep them clean and moisturized.",
  "Avoid sugary beverages like soda and opt for water, unsweetened tea, or sugar-free alternatives.",
  "Learn about the glycemic index of foods to make informed choices about how different foods affect your blood sugar.",
  "Schedule regular eye exams to monitor for any diabetes-related eye conditions.",
  "Include high-fiber foods like beans, lentils, and whole grains in your diet to help stabilize blood sugar levels.",
  "Keep track of your A1C levels as an indicator of your long-term blood sugar control.",
  "Have a plan for low blood sugar (hypoglycemia) emergencies, including fast-acting glucose sources.",
  "Build a support network of family and friends who understand your condition and can provide assistance when needed.",
  "Ensure you have an adequate supply of diabetes medications, testing supplies, and emergency snacks.",
  "Maintain good oral hygiene as diabetes can affect your dental health. Regular dental check-ups are important.",
  "Skipping meals can lead to blood sugar fluctuations. Eat regular meals and snacks as recommended.",
  "Practice stress-reduction methods like meditation or yoga to help manage stress levels.",
  "Consider consulting a registered dietitian who specializes in diabetes to create a personalized meal plan.",
  "Keep an eye on your blood pressure and work with your healthcare team to maintain it within a healthy range.",
  "Opt for heart-healthy foods like fatty fish, which is rich in omega-3 fatty acids, and foods high in antioxidants.",
];
